### ISSUE TITLE
Where's the code related to the scale-aware optimization in your paper?

### ISSUE THREAD

**Issue by Harahan** [ThisisBillhe/EfficientDM#1]
Hi, congratulations on your outstanding research being featured in the ICLR spotlight! I was reviewing your paper on scale-aware optimization and was eager to explore the associated code. However, I noticed it doesn't seem to be included in the current repository. Could you please direct me to where I might find it? Thank you!

**Comment by ThisisBillhe** [comment]
Hi, please refer to line 149-170 in quant_scripts/train_efficientdm.py

**Comment by Harahan** [comment]
Thank you for your response; I understand now.
